name: On SDK Update Dispatch

on:
  repository_dispatch:
    types: [sdk-updated]

jobs:
  log-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Log updated files from payload
        run: |
          echo "Updated files received:"
          echo "${{ github.event.client_payload.updated_files }}"
