name: On SDK Update Dispatch

on:
  repository_dispatch:
    types: [sdk-updated]

jobs:
  log-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Parse updates files from payload
        run: |
          echo "Updated files received:"
          echo "${{ github.event.client_payload.updated_files }}"
          
      - name: Run pytest on changed files
        run: |
          FILES=$(echo "$UPDATED_FILES" | tr "," " ")
          echo "Running pytest on: $FILES"
          pytest $FILES
